### ISSUE TITLE
[BUG] Doesn't seem to work with Android 14

### ISSUE THREAD

**Issue by HarriBuh** [MateusRodCosta/Share2Storage#15]
> Since the app won't even ask for essential permissions like storage access or media access, it's no wonder that the app won't show up in the share menu.
> Please fix it, I like the concept of this app.
> 
> Additionally, I'm not able to manually grant these permissions, because the app won't show up in the permission menu of Android's settings.

**Nvm, it DOES work, but just for local files. I'm confused now- why would you want to save your local files locally? This doesn't make any sense to me.
What I actually tried was to export a PDF file given out by another app to my local storage, as the original PDF could only be shared, not saved.
Doesn't Share2Storage support this task? And if not, why not? This would be the only case I needed an app like this one.**

**Comment by MateusRodCosta** [comment]
Hi, I believe I understand your scenario.

Basically, Save Locally will only show as a Share option if it's a Send intent (so usually an app initiating a Share) and if it matches the following file types:

https://github.com/MateusRodCosta/Share2Storage/blob/ea37a62b961821d15ef535d4c89c75c210781da4/app/src/main/AndroidManifest.xml#L30-L40

This should cover basic images, videos, audio and even some other commons file types such as pdf.
A good use case is, for example, if you were to get a bank statement, usually those will be PDFs but you won't be given a explicit "Save" button, only a Share button. With Save Locally you can share to the app and then  get a file picker to save whenever you want.

> Since the app won't even ask for essential permissions like storage access or media access, it's no wonder that the app won't show up in the share menu.

It doesn't need to, since it uses the native file picker of the OS.

> Additionally, I'm not able to manually grant these permissions, because the app won't show up in the permission menu of Android's settings.

The permission is unneeded, so don't worry about that.

> Nvm, it DOES work, but just for local files. I'm confused now- why would you want to save your local files locally? This doesn't make any sense to me.

Well, it works for the "Send action" type of intent and for the specified file types on the code snippet above.

>  What I actually tried was to export a PDF file given out by another app to my local storage, as the original PDF could only be shared, not saved.

PDFs should work, I would need a bit more information on what app you are using, this way I could try to figure out why it is not working.

>  Doesn't Share2Storage support this task? And if not, why not? This would be the only case I needed an app like this one.

Yes, it should support this scenario, give me more information about the app that seems to be incompatible and the file you are trying to use and I will see what I can do.

Do note that there's a small chance you are hitting this issue due to [virtual files](https://developer.android.com/training/data-storage/shared/documents-files#open-virtual-file). There's partial and not-very-well-tested support for it and the app, so it might explain things. But if it didn't show up in the Share sheet at all, it might be the intent filter.
