### ISSUE TITLE
Saved file is different in size than the original

### ISSUE THREAD

**Issue by proideo** [MateusRodCosta/Share2Storage#32]
I have noticed that the saved files are slightly larger in size than their originals. It appears that zeros are added to the end of files, increasing their size.

Tested with version 1.3.0 on two different devices and with different file types.

**Comment by MateusRodCosta** [comment]
Hi, so I believe that's a regression caused by my fix for #25.
Essentially before that I was allocating the full size of the file in memory for the copy, whcih worked fine for smaller files but failed due to memory restrictions for larger files. So I started using a 1024 bytes (1kb) buffer and released that for 1.2.3.

I believe you are hitting a problem with that: your files can't be fully fit into 1kb block so it's adding a few zeroes as extra padding at the end.
